<div class="card">
    <div class="card-header bg-primary-dark">
        <h2 class="card-title"><?=__('Need Help?') ?></h2>
    </div>
    <div class="card-body">
        <p><?=__('You can find answers for many common questions in our <a href="%s" target="_blank">support documents</a>.', 'https://www.radiolize.com/tutorials/') ?></p>

        <p><?=__('If you\'re experiencing a bug or error, you can submit a GitHub issue using the link below.') ?></p>

        <p><?=__('Your current installation type is <b>%s</b>. Be sure to include this when creating a new issue.', (\App\Settings::getInstance()->isDocker() ? 'Docker' : 'Ansible')) ?></p>
    </div>
</div>
